CREATE TABLE IF NOT EXISTS STUDENTS (
    ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    AGE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TESTS (
    ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
    ID VARCHAR(32) PRIMARY KEY,
    TEST_ID VARCHAR(32) NOT NULL,
    QUESTION varchar(225) NOT NULL,
    ANSWER varchar(225) NOT NULL,
    FOREIGN KEY (TEST_ID) REFERENCES TESTS(ID)
);

CREATE TABLE IF NOT EXISTS ENROLLMENTS (
    STUDENT_ID VARCHAR(32) NOT NULL,
    TEST_ID VARCHAR(32) NOT NULL,
    PRIMARY KEY (STUDENT_ID, TEST_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
    FOREIGN KEY (TEST_ID) REFERENCES TESTS(ID)
);